import type { NextPage, GetStaticProps } from "next";
import { useEffect } from "react";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import { getAllAnimes } from "services/Animes";
import Anime from "models/Anime";

interface Props {
  animes: Anime[];
}

const Home: NextPage<Props> = ({ animes }) => {
  useEffect(() => {
    console.log(animes);
  }, []);
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.grid}>
          {animes.map((anime) => {
            return (
              <div key={anime.id} className={styles.card}>
                <h2>{anime.attributes.canonicalTitle}</h2>
                <p>{anime.attributes.showType}</p>
              </div>
            );
          })}
        </div>
      </main>
    </div>
  );
};

export const getStaticProps: GetStaticProps<Props> = async () => {
  const animes: Anime[] = await getAllAnimes();

  return {
    props: {
      animes,
    },
    revalidate: 1,
  };
};

export default Home;
